//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ZaloPay VIPER generator
//

import UIKit

final class ___VARIABLE_moduleName___Presenter {

    // MARK: - Private properties -

    weak var view: ___VARIABLE_moduleName___ViewInterface?
    var interactor: ___VARIABLE_moduleName___InteractorInterface!
    var router: ___VARIABLE_moduleName___RouterInterface!

}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___PresenterInterface {
}
