//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the ZaloPay VIPER generator
//

import UIKit

protocol ___VARIABLE_moduleName___RouterInterface: class {
}

protocol ___VARIABLE_moduleName___ViewInterface: class {
}

protocol ___VARIABLE_moduleName___PresenterInterface: class {
}

protocol ___VARIABLE_moduleName___InteractorInterface: class {
}
